### ISSUE TITLE
how can I run this?

### ISSUE THREAD

**Issue by maxwellnewage** [Kabbura/kunafa-todo#1]
I suppose we have to use Intellij, load the project and that's all?
You should add a README.md explaining this, please!

**Comment by Kabbura** [comment]
Clone the project and then `./gradlew run` . 
It's a normal Kotlin/JS project. If you faced any issues, you can build it first using `./gradlew build`. And for continuous build (will automatically detect changes, build it and hot reload the page) use `./gradlew run -t`.
You are right. Will Add the README.md.

**Comment by maxwellnewage** [comment]
Thanks!
